### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by Gaming722** [cpm0722/transformer_pytorch#1]
https://github.com/cpm0722/transformer_pytorch/blob/76597a44348b42cb01f4728066795a4d03a1ff06/main.py#L20

If someone runs the above code and gets the following error:
```
File "/home/user_name/anaconda3/envs/transformer_pytorch/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```
Then ensuring that the `typing_extension` is version 4.5.0 may fix this bug:
```
pip install typing_extensions==4.5.0
```

**Comment by thoongee** [comment]
파이썬 가상환경내에서 bash prepare.sh 한 이후,
python3 main.py 명령어 실행했는데, 저도 동일한 issue 발생하였습니다. 에러 전문 첨부합니다.
제대로 실행하려면 어느 부분을 수정하면 되나요?

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    DATASET = Multi30k()
  File "/home/jachoi/2024AI/transformer_pytorch/data.py", line 48, in __init__
    self.tokenizer_src = self.build_tokenizer(self.lang_src)
  File "/home/jachoi/2024AI/transformer_pytorch/data.py", line 145, in build_tokenizer
    return get_tokenizer("spacy", spacy_lang_dict[lang])
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/torchtext/data/utils.py", line 115, in get_tokenizer
    spacy = spacy.load(language)
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/spacy/__init__.py", line 50, in load
    return util.load_model(
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/spacy/util.py", line 324, in load_model
    return load_model_from_package(name, **kwargs)
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/spacy/util.py", line 357, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/en_core_web_sm/__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/spacy/util.py", line 517, in load_model_from_init_py
    return load_model_from_path(
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/spacy/util.py", line 392, in load_model_from_path
    nlp = load_model_from_config(config, vocab=vocab, disable=disable, exclude=exclude)
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/spacy/util.py", line 429, in load_model_from_config
    nlp = lang_cls.from_config(
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/spacy/language.py", line 1672, in from_config
    nlp.add_pipe(
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/spacy/language.py", line 774, in add_pipe
    pipe_component = self.create_pipe(
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/spacy/language.py", line 660, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/thinc/config.py", line 746, in resolve
    resolved, _ = cls._make(
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/thinc/config.py", line 795, in _make
    filled, _, resolved = cls._fill(
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/thinc/config.py", line 850, in _fill
    filled[key], validation[v_key], final[key] = cls._fill(
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/thinc/config.py", line 849, in _fill
    promise_schema = cls.make_promise_schema(value, resolve=resolve)
  File "/home/jachoi/2024AI/transformer_pytorch/transformer2/lib/python3.8/site-packages/thinc/config.py", line 1057, in make_promise_schema
    return create_model("ArgModel", **sig_args)
  File "pydantic/main.py", line 990, in pydantic.main.create_model
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 451, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 550, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
